# Initial setup

Checking the GPU infomation

In [1]:
!nvidia-smi

Thu Nov 14 23:19:12 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 566.03                 Driver Version: 566.03         CUDA Version: 12.7     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce GTX 1650      WDDM  |   00000000:01:00.0 Off |                  N/A |
| N/A   61C    P8              4W /   54W |       1MiB /   4096MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

Check CUDA version

In [2]:
!nvcc --version

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Mon_Oct_24_19:40:05_Pacific_Daylight_Time_2022
Cuda compilation tools, release 12.0, V12.0.76
Build cuda_12.0.r12.0/compiler.31968024_0


Install pytorch

In [3]:
%pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu124

Looking in indexes: https://download.pytorch.org/whl/cu124, https://pypi.ngc.nvidia.comNote: you may need to restart the kernel to use updated packages.



Check torch version

In [4]:
import torch
print(torch.__version__)

2.5.1+cu124


# Introducion to Tensors

## What is tensor
Tensor is a way to represent data in a **numerical** way.

For example, you could represent an image as a tensor with shape [3, 224, 224] which would mean [colour_channels, height, width], as in the image has 3 colour channels (red, green, blue), a height of 224 pixels and a width of 224 pixels.

### Scalar
**Scalar** is a *single number*, it is *zero* dimension

In [5]:
# Creating tensor
scalar  = torch.tensor(7)
scalar

tensor(7)

In [6]:
# Dimension of scalar
scalar.ndim

0

In [7]:
# converse tensor back to int
scalar.item()

7

### Vector
**Vector** is a *single* dimension  but can contain many numbers. It is similar to an array of numbers

In [8]:
# vector
vector = torch.tensor([1,2,3])
vector

tensor([1, 2, 3])

We can tell the number of dimension of tensor by counting `[` 

In [9]:
vector.ndim

1

`shape` attribute tells how the elements inside tensor are arrange. The shape of the above vector will return `tourch.Size([3])`, which means there are **3** elements inside the tensor `([1,2,3])`

In [10]:
vector.shape

torch.Size([3])

### Matrix
Matrices are as flexible as vectors, except they've got an extra dimension. Matrix is similar to 2-D array

In [11]:
# MATRIX
MATRIX = torch.tensor([[2,7,8],
                      [9,10,11]])
MATRIX

tensor([[ 2,  7,  8],
        [ 9, 10, 11]])

In [12]:
MATRIX.ndim

2

This `MATRIX` has shape `touch.Size([2,3])` because it is **2** elements deep and **3** elements wide

In [13]:
MATRIX.shape

torch.Size([2, 3])

In [14]:
MATRIX[0]

tensor([2, 7, 8])

In [15]:
MATRIX[1]

tensor([ 9, 10, 11])

### Tensor
Tensors can represent almost anything, it is an **n-dimensional** array of numbers

In [16]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [17]:
TENSOR.ndim

3

In [18]:
TENSOR.shape

torch.Size([1, 3, 3])

In [19]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [20]:
TENSOR[0][0]

tensor([1, 2, 3])

In [21]:
TENSOR[0][1][2]

tensor(6)

In [22]:
TENSOR[0][2][2]

tensor(9)

> In practice, you'll often see scalars and vectors denoted as *lowercase* letters such as `y` or `a`. And matrices and tensors denoted as *uppercase* letters such as `X` or `W`.
> 
> The names matrix and tensor used interchangeably

## Random Tensors
### Why random tensor?
Machine learning models such as neural networks manipulate and seek patterns within tensors. A machine learning model often starts out with **large random** tensors of numbers and adjusts these random numbers as it works through data to better represent it.

`Start with random numbers -> look at data -> update random numbers -> repeat`

Torch random tensor - https://pytorch.org/docs/stable/generated/torch.rand.html

In [23]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.5734, 0.6561, 0.5107, 0.2216],
        [0.6140, 0.9088, 0.3600, 0.4586],
        [0.6185, 0.4502, 0.8427, 0.2894]])

In [24]:
# Create a random tensor with similar to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3)) # height, width, color_channel
random_image_size_tensor

tensor([[[0.9374, 0.5217, 0.2533],
         [0.4250, 0.5079, 0.7082],
         [0.9690, 0.5692, 0.9926],
         ...,
         [0.5389, 0.4754, 0.6624],
         [0.4446, 0.0903, 0.5690],
         [0.2147, 0.1302, 0.2986]],

        [[0.8460, 0.9570, 0.3627],
         [0.5787, 0.6512, 0.2536],
         [0.3585, 0.2148, 0.1799],
         ...,
         [0.1377, 0.0815, 0.1731],
         [0.1359, 0.1595, 0.7713],
         [0.1767, 0.9399, 0.8927]],

        [[0.9696, 0.3218, 0.8131],
         [0.7769, 0.8822, 0.0609],
         [0.6941, 0.9721, 0.8297],
         ...,
         [0.8777, 0.6674, 0.9017],
         [0.7384, 0.0100, 0.2111],
         [0.7782, 0.1699, 0.8112]],

        ...,

        [[0.9396, 0.0864, 0.7873],
         [0.3800, 0.1991, 0.9762],
         [0.9529, 0.2393, 0.7735],
         ...,
         [0.4612, 0.1188, 0.4150],
         [0.1453, 0.1011, 0.8764],
         [0.4421, 0.3343, 0.3698]],

        [[0.4423, 0.4601, 0.3442],
         [0.8408, 0.3406, 0.5831],
         [0.

In [25]:
random_image_size_tensor.ndim, random_image_size_tensor.shape

(3, torch.Size([224, 224, 3]))

### Zeros and ones

In [26]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [27]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

### Range of tensors and tensors-like

Use `torch.arange(start, end, step)` to do so.

In [28]:
# Use torch.range
one_to_nice = torch.arange(start=0, end=10,step=1)
one_to_nice

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Sometimes you might want one tensor of a certain type with the same shape as another tensor.

In [29]:
ten_zeros = torch.zeros_like(one_to_nice)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# Get information from Tensor

Three of the most common attributes you'll want to find out about tensors are:

- **shape** - what shape is the tensor? (some operations require specific shape rules)
- **dtype** - what datatype are the elements within the tensor stored in?
- **device** - what device is the tensor stored on? (usually GPU or CPU)

In [30]:
# Create a random tensor
some_tensor = torch.rand(3,4)
print(some_tensor)
print(f'shape: {some_tensor.shape}')
print(f'type: {some_tensor.dtype}')
print(f'device: {some_tensor.device}')


tensor([[0.2502, 0.9336, 0.4282, 0.2233],
        [0.5097, 0.7481, 0.4589, 0.0513],
        [0.9926, 0.6594, 0.3587, 0.1621]])
shape: torch.Size([3, 4])
type: torch.float32
device: cpu


# Tensor operations

Tensor operations include:
* Addition
* Substraction
* Multiplication
* Division
* Matrix multiplication

## Basic operations

In [31]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [32]:
# Create a tensor and subtract 10 to it
tensor = torch.tensor([1,2,3])
tensor - 10

tensor([-9, -8, -7])

In [33]:
# Create a tensor and multiply 10 to it
tensor = torch.tensor([1,2,3])
tensor * 10

tensor([10, 20, 30])

In [34]:
# Create a tensor and divide 2 to it
tensor = torch.tensor([10,20,30])
tensor / 2

tensor([ 5., 10., 15.])

## Matrix multiplication
Two main ways of performing matrix multiplication in neural networks and deep learning:
1. Element-wise multiplication
2. Matrix multiplication (dot product)

More information - https://www.mathsisfun.com/algebra/matrix-multiplying.html

In [35]:
# Element wise multiplication
tensor = torch.tensor([1,2,3])
other_tensor = torch.tensor([4,5,6])
print(f'{tensor} * {other_tensor} = {tensor * other_tensor}')

tensor([1, 2, 3]) * tensor([4, 5, 6]) = tensor([ 4, 10, 18])


In [36]:
%%time
# Matrix multiplication using torch
torch.matmul(tensor, other_tensor)

CPU times: total: 0 ns
Wall time: 3 ms


tensor(32)

In [37]:
%%time
# Matrix multiplication manually
value = 0
for i in range(len(tensor)):
    value += tensor[i] * other_tensor[i]
print(value)

tensor(32)
CPU times: total: 0 ns
Wall time: 1e+03 μs


Two rules when performing matrix multiplication:
1. The **inner dimension** must match. 
    * `(3,2) @ (3,2)` won't work
    *  `(2,3) @ (3,2)` will work
    * `(3,2) @ (2,3)` will work
2. The resulting matrix has the shape of the **outer dimensions**
    * `(2,3) @ (3,2)` -> `(2,2)`
    * `(3,2) @ (2,3)` -> `(3,3)` 
    * `(3,2) @ (2,6)` -> `(3,6)`

In [38]:
tensor_a = torch.tensor([[1,2],
                   [3,4],
                   [5,6]])

tensor_b = torch.tensor([[7,8],
                   [9,10],
                   [11,23]])

torch.matmul(tensor_a, tensor_b) # shape error

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [39]:
torch.matmul(tensor_a,tensor_b.T) # (3,2) @ (2,3) -> work

tensor([[ 23,  29,  57],
        [ 53,  67, 125],
        [ 83, 105, 193]])

In [40]:
tensor_a = torch.rand(2,3)
tensor_b = torch.rand(3,2)
tensor_c = torch.matmul(tensor_a, tensor_b)
print(f'tensor_a @ tensor_b = {tensor_c}\nShape: {tensor_c.shape}')          # size([2,2])

tensor_a @ tensor_b = tensor([[0.8167, 0.7318],
        [1.0870, 0.7900]])
Shape: torch.Size([2, 2])


In [41]:
tensor_a = torch.rand(2,3)
tensor_b = torch.rand(3,6)
tensor_c = torch.matmul(tensor_a, tensor_b)
print(f'tensor_a @ tensor_b = {tensor_c}\nShape: {tensor_c.shape}')          # size([2,6])

tensor_a @ tensor_b = tensor([[0.7246, 0.2732, 0.5059, 0.8040, 0.6476, 0.5639],
        [0.5769, 0.3542, 0.3080, 0.2568, 0.3356, 0.4479]])
Shape: torch.Size([2, 6])


## Tensor aggregations (min, max, sum, mean...)

In [42]:
x = torch.arange(start=0, end=100, step=10)
x, x.type()

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), 'torch.LongTensor')

In [43]:
# Find min and max
print(f'Min of x: {torch.min(x)} or {x.min()}')
print(f'Max of x: {torch.max(x)} or {x.max()}')
print(f'Mean of x: {torch.mean(x)}') # will get error of datatype

Min of x: 0 or 0
Max of x: 90 or 90


RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [44]:
# Cast x to dtype float32 before finding the mean
# torch.mean() requires a tensor of floating point or complex dtype
print(f'Mean of x: {torch.mean(x.type(torch.float32))} or {x.type(torch.float32).mean()}')

# Note: x remains the init style
print(f'dtype of x: {x.type()}')

Mean of x: 45.0 or 45.0
dtype of x: torch.LongTensor


In [45]:
# Find sum
print(f'Sum of x: {torch.sum(x)} or {x.sum()}')

Sum of x: 450 or 450


In [46]:
# Find median
print(f'Median of x: {torch.median(x)} or {x.median()}')

Median of x: 40 or 40


## Finding the positional of min and max

In [47]:
x, x.type()

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), 'torch.LongTensor')

We use `argmin` or `argmax` to get the **position** of the min and max

In [48]:
print(f'Min of x: {x.min()} at index: {x.argmin()}')

Min of x: 0 at index: 0


In [49]:
tensor_X = torch.rand(size=(3,4))
tensor_X

tensor([[0.7379, 0.4157, 0.4021, 0.5729],
        [0.3263, 0.3853, 0.1679, 0.6958],
        [0.5126, 0.7076, 0.0064, 0.7110]])

In [50]:
print(f'Min of tensor_X: {tensor_X.min()} at {tensor_X.argmin()}')

Min of tensor_X: 0.006448566913604736 at 10


# Reshaping, stacking, squeezing and un-squeezing tensor
* **Reshaping** - reshapes an input tensor to a defined shape
* **View** - return a view of an input tensor of certain shape but **keep the same memory** as the original tensor
* **Stacking** - combine multiple tensors on top of each other *(vstack)* or side by side *(hstack)*
* **Squeeze** - remove all `1` dimensions from a tensor
* **Unsqueeze** - add a `1` dimensions to a target tensor
* **Permute** - return a view of the input with dimensions permuted (swapped) in a certain way

## Reshape and view
When using `reshape` the number of elements in reshaped tensor and original tensor **must be equal**

In [51]:
x = torch.arange(1., 10.)
x, x.shape, x.dtype

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]), torch.float32)

In [52]:
# add an extra dimension
x_reshaped = x.reshape(1,7)
x_reshaped, x_reshaped.shape

RuntimeError: shape '[1, 7]' is invalid for input of size 9

In [53]:
# add an extra dimension
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [54]:
# add an extra dimension
x_reshaped = x.reshape(3, 3)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [55]:
# add an extra dimension
x_reshaped = x.reshape(9,1)
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [56]:
# add an extra dimension
x_reshaped = x.reshape(10,1)
x_reshaped, x_reshaped.shape

RuntimeError: shape '[10, 1]' is invalid for input of size 9

Changing the view of a tensor with `torch.view()` only creates a new view of the same tensor. So changing the view **changes the original tensor** too.

In [57]:
z = x.view(3,3)
x, z 

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]))

In [58]:
z[1,1] = 99 # change 5 -> 99 then x will be [1,2,3,4,99,6,7,8,9]
x, z, x_reshaped

(tensor([ 1.,  2.,  3.,  4., 99.,  6.,  7.,  8.,  9.]),
 tensor([[ 1.,  2.,  3.],
         [ 4., 99.,  6.],
         [ 7.,  8.,  9.]]),
 tensor([[ 1.],
         [ 2.],
         [ 3.],
         [ 4.],
         [99.],
         [ 6.],
         [ 7.],
         [ 8.],
         [ 9.]]))

## Stack

In [59]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0) # try changing dim to dim=1 and see what happens
x_stacked

tensor([[ 1.,  2.,  3.,  4., 99.,  6.,  7.,  8.,  9.],
        [ 1.,  2.,  3.,  4., 99.,  6.,  7.,  8.,  9.],
        [ 1.,  2.,  3.,  4., 99.,  6.,  7.,  8.,  9.],
        [ 1.,  2.,  3.,  4., 99.,  6.,  7.,  8.,  9.]])

In [60]:
# Stack tensors side by side of each other
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked

tensor([[ 1.,  1.,  1.,  1.],
        [ 2.,  2.,  2.,  2.],
        [ 3.,  3.,  3.,  3.],
        [ 4.,  4.,  4.,  4.],
        [99., 99., 99., 99.],
        [ 6.,  6.,  6.,  6.],
        [ 7.,  7.,  7.,  7.],
        [ 8.,  8.,  8.,  8.],
        [ 9.,  9.,  9.,  9.]])

## Squeeze and unsqueeze
Removing all single dimensions from a tensor, you can use `torch.squeeze()`

In [67]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[ 1.],
        [ 2.],
        [ 3.],
        [ 4.],
        [99.],
        [ 6.],
        [ 7.],
        [ 8.],
        [ 9.]])
Previous shape: torch.Size([9, 1])

New tensor: tensor([ 1.,  2.,  3.,  4., 99.,  6.,  7.,  8.,  9.])
New shape: torch.Size([9])


And to do the reverse of `torch.squeeze()` you can use `torch.unsqueeze()` to add a dimension value of 1 at a specific index.

In [68]:
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

## Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([ 1.,  2.,  3.,  4., 99.,  6.,  7.,  8.,  9.])
Previous shape: torch.Size([9])

New tensor: tensor([[ 1.,  2.,  3.,  4., 99.,  6.,  7.,  8.,  9.]])
New shape: torch.Size([1, 9])


## Permute
You can also rearrange the order of axes values with `torch.permute(input, dims)`, where the `input` gets turned into a view with new `dims`.
For example: you might change the tensor of an image from (height,width,color-channels) -> (color-channels,height,width)  

In [69]:
# Create tensor with specific shape
x_original = torch.rand(size=(224, 224, 3))

# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])
